# Generated by Django 3.2.6 on 2021-08-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_party_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='votes_to_skip',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
